#!/bin/sh

set -e

# Create necessary directories
mkdir -p /etc/rpi-sb-provisioner

# Set up systemd services
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# Reload systemd to pick up new service files
	deb-systemd-helper daemon-reload >/dev/null || true
	
	# Enable all services
	deb-systemd-helper enable 'provisioner-ui.service' >/dev/null || true
	deb-systemd-helper enable 'rpi-sb-provisioner@.service' >/dev/null || true
	deb-systemd-helper enable 'rpi-fde-provisioner@.service' >/dev/null || true
	deb-systemd-helper enable 'rpi-naked-provisioner@.service' >/dev/null || true
	deb-systemd-helper enable 'rpi-sb-bootstrap@.service' >/dev/null || true
	deb-systemd-helper enable 'rpi-sb-triage@.service' >/dev/null || true
	deb-systemd-helper enable 'fetch-repo-package-list@.service' >/dev/null || true
	deb-systemd-helper enable 'fetch-repo-package-list@.timer' >/dev/null || true
	deb-systemd-helper enable 'rpi-package-download@.service' >/dev/null || true
	
	# Start the services that should be running by default
	if [ -d /run/systemd/system ]; then
		deb-systemd-invoke start 'provisioner-ui.service' >/dev/null || true
		deb-systemd-invoke start 'fetch-repo-package-list@.timer' >/dev/null || true
	fi
fi

#DEBHELPER#