#!/bin/sh

set -e

# Stop and disable the services
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	# Stop all services
	deb-systemd-invoke stop 'rpi-provisioner-ui.service' >/dev/null || true
fi

if [ "$1" = "remove" ]; then
	# Disable and clean up all services
	deb-systemd-helper disable 'rpi-provisioner-ui.service' >/dev/null || true
	deb-systemd-helper disable 'rpi-sb-provisioner@.service' >/dev/null || true
	deb-systemd-helper disable 'rpi-fde-provisioner@.service' >/dev/null || true
	deb-systemd-helper disable 'rpi-naked-provisioner@.service' >/dev/null || true
	deb-systemd-helper disable 'rpi-sb-bootstrap@.service' >/dev/null || true
	deb-systemd-helper disable 'rpi-sb-triage@.service' >/dev/null || true
	deb-systemd-helper disable 'fetch-repo-package-list@.service' >/dev/null || true
	deb-systemd-helper disable 'fetch-repo-package-list@.timer' >/dev/null || true
	deb-systemd-helper disable 'rpi-package-download@.service' >/dev/null || true
	
	deb-systemd-helper unmask 'rpi-provisioner-ui.service' >/dev/null || true
	deb-systemd-helper unmask 'rpi-sb-provisioner@.service' >/dev/null || true
	deb-systemd-helper unmask 'rpi-fde-provisioner@.service' >/dev/null || true
	deb-systemd-helper unmask 'rpi-naked-provisioner@.service' >/dev/null || true
	deb-systemd-helper unmask 'rpi-sb-bootstrap@.service' >/dev/null || true
	deb-systemd-helper unmask 'rpi-sb-triage@.service' >/dev/null || true
	deb-systemd-helper unmask 'fetch-repo-package-list@.service' >/dev/null || true
	deb-systemd-helper unmask 'fetch-repo-package-list@.timer' >/dev/null || true
	deb-systemd-helper unmask 'rpi-package-download@.service' >/dev/null || true
	
	deb-systemd-helper daemon-reload >/dev/null || true
fi

#DEBHELPER# 