#!/bin/sh

set -e

# Stop and disable the service
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'provisioner.service' >/dev/null || true
fi

if [ "$1" = "remove" ]; then
	deb-systemd-helper disable 'provisioner.service' >/dev/null || true
	deb-systemd-helper unmask 'provisioner.service' >/dev/null || true
	deb-systemd-helper daemon-reload >/dev/null || true
fi

#DEBHELPER# 