= Confguration variables
:toc:
:toc-title: Table of Contents
:toclevels: 3

This document describes the configuration variables used in /etc/rpi-sb-provisioner/config. You do not typically need to set these variables, and they are set by the WebUI. You may manually set them if you want to use a change management system or similar to update them.

== Variables

=== PROVISIONING_STYLE
*Mandatory, with a default*

Select the provisioning style you wish to use. Supported values are `secure-boot`, `fde-only` and `naked`.

If `PROVISIONING_STYLE` is not specified, it defaults to `secure-boot`.

=== CUSTOMER_KEY_FILE_PEM
*Optional, mandatory if CUSTOMER_KEY_PKCS11_NAME is not set*

The fully qualified path to your signing key, encoded in PEM format. This file is expected to contain an RSA 2048-bit Private Key.

WARNING: This file should be considered key material, and should be protected while at rest and in use according to your threat model.

=== CUSTOMER_KEY_PKCS11_NAME
*Optional, mandatory if CUSTOMER_KEY_FILE_PEM is not set*

The keypair alias for a PKCS11 keypair, typically stored on a Hardware Security Module (HSM) and provided through a helper tool. This is expected to act in place of the RSA 2048-bit Private key specified with CUSTOMER_KEY_FILE_PEM, and will be used as the signing device for all future pre-boot authentication images.

The value should take the format:

----
'pkcs11:object=<keypair-alias>;type=private'
----

WARNING: You must use single quotes to enclose the value, and URI encode the value

WARNING: The PKCS11 provider, and it's associated HSM, should be considered key material and should be protected while at rest and in use according to your threat model.

=== GOLD_MASTER_OS_FILE
*Mandatory*

This should be your 'gold master' OS image. No customisation should be present in this image that you would not expect to be deployed to your entire fleet. `rpi-sb-provisioner` assumes this image has been created using `pi-gen`, and using a non-`pi-gen` image may produce undefined behaviour.

WARNING: This file *must* be the uncompressed image.

=== RPI_DEVICE_STORAGE_TYPE
*Mandatory*

Specify the kind of storage your target will use. Supported values are `sd`, `emmc`, `nvme`.

=== RPI_DEVICE_STORAGE_CIPHER
*Optional*

Specify the full-disk-encryption cipher. Supported values are `aes-xts-plain64`, `xchacha12,aes-adiantum-plain64`.

If `RPI_DEVICE_STORAGE_CIPHER` is not specified, it defaults to `aes-xts-plain64`.

`aes-xts-plain64` is recommended for Raspberry Pi 5 family devices (including Compute Module 5); all other Raspberry Pi devices are recommended to use `xchacha12,aes-adiantum-plain64` for improved performance.

=== RPI_DEVICE_FAMILY
*Mandatory*

Specify the family of Raspberry Pi device you are provisioning. Supported values are `4, 5, 2W`. For example:

* A Raspberry Pi Compute Module 4 would be family `4`
* A Raspberry Pi 5 would be family `5`
* A Raspberry Pi Compute Module 5 would be family `5`
* A Raspberry Pi Zero 2 W would be family `2W`

=== RPI_DEVICE_BOOTLOADER_CONFIG_FILE
*Mandatory, with a default*

WARNING: `rpi-sb-provisioner` will ignore the Raspberry Pi Bootloader configuration built by `pi-gen`, and use the one provided in this variable.

Specify the Raspberry Pi Bootloader configuration you want your provisioned devices to use. A default is provided.

Further information on the format of this configuration file can be found in the Raspberry Pi Documentation, at https://www.raspberrypi.com/documentation/computers/config_txt.html

=== RPI_DEVICE_LOCK_JTAG
*Optional*

Raspberry Pi devices have a mechanism to restrict JTAG access to the device.

Note that using this function will prevent Raspberry Pi engineers from being able to assist in debugging your device, should you request assitance.

Set to any value to enable the JTAG restrictions.

=== RPI_DEVICE_EEPROM_WP_SET
*Optional*

Raspberry Pi devices that use an EEPROM as part of their boot flow can configure that EEPROM to enable write protection - preventing modification.

Set to any value to enable EEPROM write protection.

=== RPI_SB_PROVISIONER_MANUFACTURING_DB
*Optional*

Store manufacturing data in a sqlite3 database. This will include the board serial, board revision, the boot ROM version, the MAC address of the ethernet port, any set hash of the customer signing key, the JTAG lock state, the board attributes and the advanced boot flags.

You must not specify the path of a database stored on a network drive or similar storage, as this mechanism is only safe to use on a single provisioning system. For merging the output with multiple provisioning systems, consider "Processing the manufacturing database" later in this document.

Set to the path of a file to contain a SQLite database stored on local storage. The WebUI will create this file if it does not exist.

WARNING: If you are not using the WebUI, you must create this file before execution, for example using `touch`:

----
$ touch ${RPI_SB_PROVISIONER_MANUFACTURING_DB}
----

=== RPI_DEVICE_RETRIEVE_KEYPAIR
*Optional*

Specify a directory to copy the device unique keypair to. The keys will be named <serial>.der and <serial>.pub

Set to the path of a directory to use, otherwise keys will be stored alongside provisioning logs in a directory named "keypair".

NOTE: These keys are sensitive key material, and you must ensure they are handled appropriately.

=== RPI_SB_WORKDIR
*Optional*

WARNING: If you do not set this variable, your modified OS intermediates will not be stored, and will be unavailable for inspection.

Set to a location to cache OS assets between provisioning sessions. Recommended for use in production. For example:

----
RPI_SB_WORKDIR=/srv/rpi-sb-provisioner/
----

== Format of the config file

The config file is a simple text file, with one variable per line. Variables are specified in the format:

----
VARIABLE_NAME=value
----

For example:

----
RPI_SB_PROVISIONER_MANUFACTURING_DB=/var/lib/rpi-sb-provisioner/manufacturing.db
----

Comments can be added to the file by starting a line with a `#` character.

----
# This is a comment
RPI_SB_PROVISIONER_MANUFACTURING_DB=/var/lib/rpi-sb-provisioner/manufacturing.db
----
